// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/spf13/viper"
	"kkako_video/internal/user_repo/handler"
	"kkako_video/internal/user_repo/repo"
	"kkako_video/internal/user_repo/server"
	"kkako_video/pkg/app"
)

// Injectors from wire.go:

func initApp(v *viper.Viper) (*app.App, error) {
	iUserRepo := repo.NewUserRepo()
	userRepoHandler := handler.NewUserRepoHandler(iUserRepo)
	grpcServer := server.NewGrpcServer(userRepoHandler)
	appApp, err := newApp(grpcServer)
	if err != nil {
		return nil, err
	}
	return appApp, nil
}
